### ISSUE TITLE
Run recursive URL parsing on a Wikipedia page with varying depths

### ISSUE THREAD

**Issue by dilithjay** [oidlabs-com/Lexoid#30]

**Comment by dilithjay** [comment]
Results on the [Wikipedia Main Page](https://en.wikipedia.org/wiki/Main_Page):

Depth | URLs crawled | Time taken
--- | --- | ---
1 | 1 | 0.8s
2 | 89 | 1m 24.6s
3 | 139 | 1m 51.6s
4 | 647 | 8m 48.4s
5 | 1543 | 17m 44.6s

**Comment by pramitchoudhary** [comment]
Above was in `AUTO` mode?

**Comment by dilithjay** [comment]
> Above was in `AUTO` mode?

I didn't specify the mode because it doesn't matter for parsing URLs. We read the HTML and convert it to markdown.

However, that does bring up a possible improvement to the implementation: If there is a hyperlink to a PDF, do we want to download that and parse it? We currently don't. If we do, then the parser type becomes relevant. I'll make the changes to support it.

**Comment by pramitchoudhary** [comment]
Ah good point. In a headless way, it makes sense for us to be supporting different hyperlinks. We create a ticket for that?

**Comment by dilithjay** [comment]
Created: #32
